
name: Generate Doxygen Documentation

on:
  push:
    branches:
      - master   # or your default branch
    paths:
      - '**.h'       # Monitor header file changes
      - '**.c'       # Monitor source file changes
      - 'Doxyfile'   # Monitor Doxygen config changes
      - 'doc/pages/**'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      KOS_BASE: ${{ github.workspace }}  # Sets KOS_BASE to the repository root
      KOS_ARCH: dreamcast

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Doxygen
        run: sudo apt install -y wget graphviz

      - name: Install Doxygen 1.11.0
        run: |
          wget https://github.com/doxygen/doxygen/releases/download/Release_1_11_0/doxygen-1.11.0.linux.bin.tar.gz
          tar -xzf doxygen-1.11.0.linux.bin.tar.gz
          sudo mv doxygen-1.11.0/bin/* /usr/local/bin/
          rm -rf doxygen-1.11.0*

      - name: Verify Doxygen Version
        run: doxygen --version

      - name: Create Output Directory for Doxygen
        run: mkdir -p doc/reference

      - name: Generate Documentation
        run: doxygen doc/Doxyfile

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./doc/reference/html    # Adjust to match your OUTPUT_DIRECTORY/html
