name: KOS Check on PRs

on:
  pull_request:
    branches:
      - master
    paths:
      - 'include/**'
      - 'kernel/**'
      - 'addons/**'
      - 'utils/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain:
          - "13.3-legacy"
          - "14.2-stable"
          - "15.0-dev"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Convert Repository Owner to Lowercase
        id: lower-owner
        run: |
          echo "repository_owner=${GITHUB_REPOSITORY%%/*}" | tr '[:upper:]' '[:lower:]' >> $GITHUB_OUTPUT

      - name: Pull Toolchain Image
        run: |
          docker pull ghcr.io/${{ steps.lower-owner.outputs.repository_owner }}/dc-toolchain:${{ matrix.toolchain }}

      - name: Build SDK
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/opt/toolchains/dc/kos \
            -w /opt/toolchains/dc/kos \
            ghcr.io/${{ steps.lower-owner.outputs.repository_owner }}/dc-toolchain:${{ matrix.toolchain }} \
            "source environ.sh.master && make all V=1 | tee build.log"

      - name: Upload Build Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs-${{ matrix.toolchain }}-pr-${{ github.event.pull_request.number }}-${{ github.run_id }}
          path: build.log

